- name: create app
  shell: /bin/zsh -lc "composer create-project --prefer-dist laravel/laravel {{ project_name }}" chdir={{ document_root }}
  sudo: vagrant
  ignore_errors: true

- name: composer update
  shell: /bin/zsh -lc "composer update" chdir={{ document_root }}{{ project_name }}
  sudo: vagrant
  ignore_errors: true

- name: .env key generate
  shell: /bin/zsh -lc "php artisan key:generate" chdir={{ document_root }}{{ project_name }}
