---
# インストールするツール
tool_install_list:
  - vim

# プロジェクト名
project_name: 'comsize_laravel'

# Ansible実行ファイル
ansible_file_path: 'ansible/site.yml'

# ホスト
hostname: laravel.comsize.com

# ipアドレス
ip: 192.168.33.55

# WEBフォルダ共有設定
sync_folder:   'www/'
document_root: '/var/www/'